CREATE DATABASE INFORMATION;
USE INFORMATION;

CREATE TABLE SALES
(
PURCHASE_NUMBER INT NOT NULL AUTO_INCREMENT,
PURCHASE_DATE DATE NOT NULL,
CUSTOMER_ID INT,
ITEM_CODE VARCHAR(10),
PRIMARY KEY (PURCHASE_NUMBER)
);

ALTER TABLE SALES
ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE;

ALTER TABLE SALES
ADD FOREIGN KEY (ITEM_CODE) REFERENCES ITEMS(ITEM_CODE) ON DELETE CASCADE;

CREATE TABLE CUSTOMERS
(
CUSTOMER_ID INT(10),
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
EMAIL_ID VARCHAR(255),
COMPLAINT INT(15),
PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE ITEMS
(
ITEM_CODE VARCHAR(255),
ITEM VARCHAR(255),
UNIT_PRICE NUMERIC(10,2),
COMPANY_ID VARCHAR(255),
PRIMARY KEY (ITEM_CODE)
);

ALTER TABLE ITEMS
ADD FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(COMPANY_ID) ON DELETE CASCADE;

CREATE TABLE COMPANY
(
COMPANY_ID VARCHAR(255),
COMPANY_NAME VARCHAR(255),
HQ_NUMBER INT(12),
PRIMARY KEY (COMPANY_ID)
);
